### ISSUE TITLE
Dimension error when I train with images of size 64

### ISSUE THREAD

**Issue by Oushesh** [avirambh/MSDNet-GCN#6]
Hi Avirambh,

How did you come up with 128 for self.inner_channels; line 418 in msdnet_layers.py?

I tried to run the code with image input size at 64 instead of 32 with 256 self.inner channels but I get an error?

Could you explain how you come up with 128 based on image size 32 from the beginning?

Cheers,
Oushesh

**Comment by avirambh** [comment]
Hi @Oushesh,
Sorry for the late response.

This [value](https://github.com/avirambh/MSDNet-GCN/blob/master/models/msdnet_layers.py#L417) represents the number of inner channels in the classifier network.
It is taken from the [paper (section A, page 13)](https://arxiv.org/pdf/1703.09844.pdf) and the [Lua implementation](https://github.com/gaohuang/MSDNet/blob/master/models/JointTrainContainer.lua#L62).

I hope this helps,
Aviram
